ucas:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: chatucas
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 123456
